name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
# change to write if auto committing
permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Git long paths
        run: git config --global core.longpaths true

      - name: Configure Git to handle symlinks
        run: git config --global core.symlinks false

      - uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install
        working-directory: repo

      - name: Run Pint
        run: vendor/bin/pint
        working-directory: repo

      - name: Check Frontend Formatting
        run: npm run format:check
        working-directory: repo

      - name: Lint Frontend
        run: npm run lint
        working-directory: repo

      # Uncomment if auto committing is enabled
      # - name: Format Frontend
      #   run: npm run format
      #   working-directory: repo

      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
